[versions]
agp = "9.0.0"
kotlin = "2.3.0"
googleServices = "4.4.4"
huaweiAgcp = "1.9.1.301"
firebaseCrashlyticsGradle = "3.0.6"
androidxCore = "1.17.0"
androidxPalette = "1.0.0"
androidxExifinterface = "1.4.2"
androidxDynamicanimation = "1.1.0"
androidxSharetarget = "1.2.0"
androidxInterpolator = "1.0.0"
androidxBiometric = "1.1.0"
gmsCastFramework = "21.4.0"
androidxMediarouter = "1.8.1"
nanohttpd = "2.3.1"
checkerQual = "3.53.0"
checkerCompatQual = "2.5.6"
firebaseMessaging = "25.0.1"
firebaseConfig = "23.0.1"
firebaseDatatransport = "20.0.0"
firebaseAppindexing = "20.0.0"
playServicesMaps = "20.0.0"
playServicesAuth = "21.5.0"
playServicesVision = "20.1.3"
playServicesWearable = "19.0.0"
playServicesLocation = "21.3.0"
playServicesWallet = "19.5.0"
isoparser = "1.1.22"
stripeAndroid = "22.6.0"
mlkitLanguageId = "17.0.6"
billing = "8.3.0"
gson = "2.13.2"
guava = "33.5.0-android"
playIntegrity = "1.6.0"
playServicesSafetynet = "18.0.1"
playServicesMlkitSubjectSegmentation = "16.0.0-beta1"
playServicesMlkitImageLabeling = "16.0.8"
androidxCredentials = "1.5.0"
androidxCredentialsPlayServicesAuth = "1.5.0"
recaptcha = "18.8.0"
desugarJdkLibs = "2.1.5"
androidxFragment = "1.8.9"
androidxCoreKtx = "1.17.0"
huaweiPush = "6.13.0.300"
huaweiMaps = "6.15.1.317"
huaweiLocation = "6.16.0.302"
appcenterDistribute = "5.0.6"
appcenterCrashes = "5.0.6"
appcenterAnalytics = "5.0.6"
junit = "4.13.2"
androidxTestExtJunit = "1.2.1"
androidxTestRunner = "1.7.0"
kotlinTest = "2.3.0"
kotlinTestJunit = "2.3.0"
fixture = "1.2.0"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
huaweiAgconnect = { id = "com.huawei.agconnect", version.ref = "huaweiAgcp" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" }

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-palette = { group = "androidx.palette", name = "palette", version.ref = "androidxPalette" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "androidxExifinterface" }
androidx-dynamicanimation = { group = "androidx.dynamicanimation", name = "dynamicanimation", version.ref = "androidxDynamicanimation" }
androidx-sharetarget = { group = "androidx.sharetarget", name = "sharetarget", version.ref = "androidxSharetarget" }
androidx-interpolator = { group = "androidx.interpolator", name = "interpolator", version.ref = "androidxInterpolator" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "androidxBiometric" }
gms-play-services-cast-framework = { group = "com.google.android.gms", name = "play-services-cast-framework", version.ref = "gmsCastFramework" }
androidx-mediarouter = { group = "androidx.mediarouter", name = "mediarouter", version.ref = "androidxMediarouter" }
nanohttpd = { group = "org.nanohttpd", name = "nanohttpd", version.ref = "nanohttpd" }
checker-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerQual" }
checker-compat-qual = { group = "org.checkerframework", name = "checker-compat-qual", version.ref = "checkerCompatQual" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
firebase-config = { group = "com.google.firebase", name = "firebase-config", version.ref = "firebaseConfig" }
firebase-datatransport = { group = "com.google.firebase", name = "firebase-datatransport", version.ref = "firebaseDatatransport" }
firebase-appindexing = { group = "com.google.firebase", name = "firebase-appindexing", version.ref = "firebaseAppindexing" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
play-services-vision = { group = "com.google.android.gms", name = "play-services-vision", version.ref = "playServicesVision" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
play-services-wallet = { group = "com.google.android.gms", name = "play-services-wallet", version.ref = "playServicesWallet" }
mp4parser-isoparser = { group = "com.googlecode.mp4parser", name = "isoparser", version.ref = "isoparser" }
stripe-android = { group = "com.stripe", name = "stripe-android", version.ref = "stripeAndroid" }
mlkit-language-id = { group = "com.google.mlkit", name = "language-id", version.ref = "mlkitLanguageId" }
billing = { group = "com.android.billingclient", name = "billing", version.ref = "billing" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
play-integrity = { group = "com.google.android.play", name = "integrity", version.ref = "playIntegrity" }
play-services-safetynet = { group = "com.google.android.gms", name = "play-services-safetynet", version.ref = "playServicesSafetynet" }
play-services-mlkit-subject-segmentation = { group = "com.google.android.gms", name = "play-services-mlkit-subject-segmentation", version.ref = "playServicesMlkitSubjectSegmentation" }
play-services-mlkit-image-labeling = { group = "com.google.android.gms", name = "play-services-mlkit-image-labeling", version.ref = "playServicesMlkitImageLabeling" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "androidxCredentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidxCredentialsPlayServicesAuth" }
recaptcha = { group = "com.google.android.recaptcha", name = "recaptcha", version.ref = "recaptcha" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "androidxFragment" }
huawei-push = { group = "com.huawei.hms", name = "push", version.ref = "huaweiPush" }
huawei-maps = { group = "com.huawei.hms", name = "maps", version.ref = "huaweiMaps" }
huawei-location = { group = "com.huawei.hms", name = "location", version.ref = "huaweiLocation" }
appcenter-distribute = { group = "com.microsoft.appcenter", name = "appcenter-distribute", version.ref = "appcenterDistribute" }
appcenter-crashes = { group = "com.microsoft.appcenter", name = "appcenter-crashes", version.ref = "appcenterCrashes" }
appcenter-analytics = { group = "com.microsoft.appcenter", name = "appcenter-analytics", version.ref = "appcenterAnalytics" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlinTestJunit" }
fixture = { group = "com.appmattus.fixture", name = "fixture", version.ref = "fixture" }